[package]
name = "motiongfx_core_macros"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
motiongfx_macro_utils = { path = "../../motiongfx_macro_utils" }

[lints]
workspace = true
