[package]
name = "motiongfx_vello"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
motiongfx_core = { path = "../motiongfx_core" }
motiongfx_vello_macros = { path = "macros" }
bevy_vello_graphics = { path = "../bevy_vello_graphics" }

bevy = "0.13"
bevy_vello = "0.3"

[lints]
workspace = true
